# -*- coding: utf-8 -*-
"""Modelo_Score_Turismo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5FSTO7r5h-U_MIqCtKF-BkSoxglazw0
"""

import pandas as pd
import numpy as np
import pickle
import json
import os
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ─────────────────────────────────────────────
# 1. CARGA DE DATOS
# ─────────────────────────────────────────────
print("="*60)
print("1. CARGANDO DATOS")
print("="*60)

BASE = "/content"

df_visitas  = pd.read_csv(f"{BASE}/tb_visitas.csv", parse_dates=["fecha_visita"])
df_lugares  = pd.read_csv(f"{BASE}/tb_lugares.csv")
df_usuarios = pd.read_csv(f"{BASE}/tb_usuarios.csv")
df_clima    = pd.read_csv(f"{BASE}/tb_clima_historico.csv", parse_dates=["fecha"])

print(f"  Visitas:  {len(df_visitas):>5} registros")
print(f"  Lugares:  {len(df_lugares):>5} registros")
print(f"  Usuarios: {len(df_usuarios):>5} registros")
print(f"  Clima:    {len(df_clima):>5} registros")

# ─────────────────────────────────────────────
# 2. CONSTRUCCIÓN DEL DATASET DE ENTRENAMIENTO
#    (JOIN de todas las tablas)
# ─────────────────────────────────────────────
print("\n" + "="*60)
print("2. CONSTRUCCIÓN DEL DATASET")
print("="*60)

# Join visitas + lugares
df = df_visitas.merge(
    df_lugares[[
        "lugar_id","categoria","subcategoria","altitud_msnm",
        "precio_entrada_cop","capacidad_max_dia","dificultad_acceso",
        "clima_predominante","calificacion_promedio"
    ]],
    on="lugar_id", how="left"
)

# Join + usuarios
df = df.merge(
    df_usuarios[[
        "usuario_id","edad","genero","ciudad_origen",
        "presupuesto_preferido","categoria_favorita",
        "nivel_actividad_fisica","viaja_con","num_visitas_total"
    ]],
    on="usuario_id", how="left"
)

# Join + clima (por municipio más cercano al lugar — simplificado por fecha)
# Usamos el clima promedio del día de visita a nivel Caldas
clima_diario = df_clima.groupby("fecha").agg(
    temp_max_prom=("temperatura_max_c","mean"),
    temp_min_prom=("temperatura_min_c","mean"),
    precip_prom  =("precipitacion_mm","mean"),
    temporada    =("temporada", lambda x: x.mode()[0])
).reset_index()

df = df.merge(clima_diario, left_on="fecha_visita", right_on="fecha", how="left")
df["temp_max_prom"] = df["temp_max_prom"].fillna(df["temp_max_prom"].median())
df["temp_min_prom"] = df["temp_min_prom"].fillna(df["temp_min_prom"].median())
df["precip_prom"]   = df["precip_prom"].fillna(df["precip_prom"].median())
df["temporada"]     = df["temporada"].fillna("media")

print(f"  Dataset combinado: {len(df)} filas x {len(df.columns)} columnas")

# ─────────────────────────────────────────────
# 3. FEATURE ENGINEERING
#    (crear variables que el modelo pueda usar)
# ─────────────────────────────────────────────
print("\n" + "="*60)
print("3. FEATURE ENGINEERING")
print("="*60)

# Variable objetivo: calificacion_dada (score 1-5)
TARGET = "calificacion_dada"

# ── Feature: ¿el usuario visitó su categoría favorita?
df["match_categoria"] = (df["categoria_favorita"] == df["categoria"]).astype(int)
print("  ✓ match_categoria (usuario vs lugar)")

# ── Feature: ¿el presupuesto del usuario es compatible con el precio?
presup_map = {"bajo": 50000, "medio": 150000, "alto": 999999}
df["presupuesto_max"] = df["presupuesto_preferido"].map(presup_map)
df["precio_compatible"] = (df["precio_entrada_cop"] <= df["presupuesto_max"]).astype(int)
print("  ✓ precio_compatible (presupuesto vs precio entrada)")

# ── Feature: ¿el nivel de actividad es compatible con la dificultad?
act_map  = {"bajo": 1, "medio": 2, "alto": 3}
dif_map  = {"fácil": 1, "moderado": 2, "difícil": 3}
df["nivel_act_num"] = df["nivel_actividad_fisica"].map(act_map)
df["dificultad_num"] = df["dificultad_acceso"].map(dif_map)
df["actividad_compatible"] = (df["nivel_act_num"] >= df["dificultad_num"]).astype(int)
print("  ✓ actividad_compatible (nivel actividad vs dificultad acceso)")

# ── Feature: día de fin de semana
df["es_fin_semana"] = df["dia_semana"].isin(["sábado","domingo"]).astype(int)
print("  ✓ es_fin_semana")

# ── Feature: clima favorable (soleado o nublado = ok; lluvioso/tormenta = malo)
df["clima_favorable"] = df["clima_dia_visita"].isin(["soleado","nublado"]).astype(int)
print("  ✓ clima_favorable")

# ── Feature: ratio de ocupación estimada del día
# (usamos visitas promedio históricas / capacidad)
visitas_prom = df.groupby("lugar_id")["visita_id"].count() / df["fecha_visita"].nunique()
df["ocupacion_estimada"] = df["lugar_id"].map(visitas_prom).fillna(0.5)
print("  ✓ ocupacion_estimada")

# ── Codificación de variables categóricas (Label Encoding)
categoricas = [
    "categoria","dificultad_acceso","clima_predominante",
    "presupuesto_preferido","categoria_favorita",
    "nivel_actividad_fisica","viaja_con","temporada",
    "clima_dia_visita","comentario_sentimiento"
]

encoders = {}
for col in categoricas:
    le = LabelEncoder()
    df[col + "_enc"] = le.fit_transform(df[col].astype(str))
    encoders[col] = le

print(f"  ✓ {len(categoricas)} variables categóricas codificadas")

# ─────────────────────────────────────────────
# 4. SELECCIÓN DE FEATURES PARA EL MODELO
# ─────────────────────────────────────────────
FEATURES = [
    # Del lugar
    "altitud_msnm", "precio_entrada_cop", "capacidad_max_dia",
    "calificacion_promedio", "dificultad_num",
    "categoria_enc", "clima_predominante_enc",
    # Del usuario
    "edad", "num_visitas_total", "nivel_act_num",
    "presupuesto_preferido_enc", "categoria_favorita_enc",
    "viaja_con_enc",
    # De la visita
    "mes", "es_festivo", "es_fin_semana", "duracion_horas",
    "gasto_total_cop", "clima_dia_visita_enc", "clima_favorable",
    # Features engineered
    "match_categoria", "precio_compatible", "actividad_compatible",
    "ocupacion_estimada",
    # Del clima
    "temp_max_prom", "precip_prom", "temporada_enc",
]

X = df[FEATURES].copy()
y = df[TARGET].copy()

print(f"\n  Features seleccionadas: {len(FEATURES)}")
print(f"  Variable objetivo:      {TARGET} (rango: {y.min()}-{y.max()})")

# ─────────────────────────────────────────────
# 5. DIVISIÓN TRAIN / TEST
# ─────────────────────────────────────────────
print("\n" + "="*60)
print("4. DIVISIÓN TRAIN / TEST (80% / 20%)")
print("="*60)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"  Train: {len(X_train)} muestras")
print(f"  Test:  {len(X_test)} muestras")

# ─────────────────────────────────────────────
# 6. ENTRENAMIENTO DEL MODELO
# ─────────────────────────────────────────────
print("\n" + "="*60)
print("5. ENTRENAMIENTO — Random Forest Regressor")
print("="*60)

modelo = RandomForestRegressor(
    n_estimators=200,       # 200 árboles
    max_depth=12,           # profundidad controlada (evita overfitting)
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",    # estándar para RF
    random_state=42,
    n_jobs=-1               # usa todos los núcleos disponibles
)

modelo.fit(X_train, y_train)
print("  ✓ Modelo entrenado con 200 árboles, max_depth=12")

# ─────────────────────────────────────────────
# 7. EVALUACIÓN
# ─────────────────────────────────────────────
print("\n" + "="*60)
print("6. EVALUACIÓN DEL MODELO")
print("="*60)

y_pred_train = modelo.predict(X_train)
y_pred_test  = modelo.predict(X_test)

mae_train  = mean_absolute_error(y_train, y_pred_train)
mae_test   = mean_absolute_error(y_test,  y_pred_test)
rmse_train = np.sqrt(mean_squared_error(y_train, y_pred_train))
rmse_test  = np.sqrt(mean_squared_error(y_test,  y_pred_test))
r2_train   = r2_score(y_train, y_pred_train)
r2_test    = r2_score(y_test,  y_pred_test)

# Cross-validation (5 folds)
cv_scores = cross_val_score(modelo, X, y, cv=5, scoring="r2", n_jobs=-1)

print(f"\n  {'Métrica':<25} {'Train':>10} {'Test':>10}")
print(f"  {'-'*47}")
print(f"  {'MAE (error promedio)':<25} {mae_train:>10.4f} {mae_test:>10.4f}")
print(f"  {'RMSE':<25} {rmse_train:>10.4f} {rmse_test:>10.4f}")
print(f"  {'R² Score':<25} {r2_train:>10.4f} {r2_test:>10.4f}")
print(f"\n  Cross-Validation R² (5 folds): {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
print(f"  Scores por fold: {[round(s,3) for s in cv_scores]}")

# Interpretación del MAE
print(f"\n  📊 Interpretación: el modelo se equivoca en promedio")
print(f"     ±{mae_test:.2f} puntos en una escala del 1 al 5")

# ─────────────────────────────────────────────
# 8. IMPORTANCIA DE FEATURES
# ─────────────────────────────────────────────
print("\n" + "="*60)
print("7. IMPORTANCIA DE VARIABLES (Top 15)")
print("="*60)

importancias = pd.DataFrame({
    "feature":    FEATURES,
    "importance": modelo.feature_importances_
}).sort_values("importance", ascending=False).reset_index(drop=True)

print(f"\n  {'#':<4} {'Variable':<30} {'Importancia':>12} {'Barra'}")
print(f"  {'-'*65}")
for i, row in importancias.head(15).iterrows():
    barra = "█" * int(row["importance"] * 200)
    print(f"  {i+1:<4} {row['feature']:<30} {row['importance']:>12.4f}  {barra}")

# ─────────────────────────────────────────────
# 9. FUNCIÓN DE PREDICCIÓN / RECOMENDACIÓN
#    (Esta es la que usará el Backend en la API)
# ─────────────────────────────────────────────
print("\n" + "="*60)
print("8. DEMO — SISTEMA DE RECOMENDACIÓN")
print("="*60)

def predecir_score_para_usuario(usuario_id, encoders_dict, modelo_rf, df_lug, df_usr, top_n=5):
    """
    Given a user_id, predicts the score that user would give
    to each tourist place and returns the ranking of recommendations.
    """
    usuario = df_usr[df_usr["usuario_id"] == usuario_id].iloc[0]
    resultados = []

    for _, lugar in df_lug.iterrows():
        # Construir la fila de features para este par usuario-lugar
        presup_max_val = presup_map.get(usuario["presupuesto_preferido"], 100000)
        nivel_act_val  = act_map.get(usuario["nivel_actividad_fisica"], 2)
        dificultad_val = dif_map.get(lugar["dificultad_acceso"], 2)

        fila = {
            "altitud_msnm":             lugar["altitud_msnm"],
            "precio_entrada_cop":        lugar["precio_entrada_cop"],
            "capacidad_max_dia":         lugar["capacidad_max_dia"],
            "calificacion_promedio":     lugar["calificacion_promedio"],
            "dificultad_num":            dificultad_val,
            "categoria_enc":             encoders_dict["categoria"].transform([lugar["categoria"]])[0],
            "clima_predominante_enc":    encoders_dict["clima_predominante"].transform([lugar["clima_predominante"]])[0],
            "edad":                      usuario["edad"],
            "num_visitas_total":         usuario["num_visitas_total"],
            "nivel_act_num":             nivel_act_val,
            "presupuesto_preferido_enc": encoders_dict["presupuesto_preferido"].transform([usuario["presupuesto_preferido"]])[0],
            "categoria_favorita_enc":    encoders_dict["categoria_favorita"].transform([usuario["categoria_favorita"]])[0],
            "viaja_con_enc":             encoders_dict["viaja_con"].transform([usuario["viaja_con"]])[0],
            "mes":                       pd.Timestamp.now().month,
            "es_festivo":                0,
            "es_fin_semana":             1 if pd.Timestamp.now().weekday() >= 5 else 0,
            "duracion_horas":            3.0,
            "gasto_total_cop":           min(lugar["precio_entrada_cop"] + 30000, presup_max_val),
            "clima_dia_visita_enc":      encoders_dict["clima_dia_visita"].transform(["soleado"])[0],
            "clima_favorable":           1,
            "match_categoria":           int(usuario["categoria_favorita"] == lugar["categoria"]),
            "precio_compatible":         int(lugar["precio_entrada_cop"] <= presup_max_val),
            "actividad_compatible":      int(nivel_act_val >= dificultad_val),
            "ocupacion_estimada":        0.3,
            "temp_max_prom":             18.0,
            "precip_prom":               5.0,
            "temporada_enc":             encoders_dict["temporada"].transform(["media"])[0],
        }

        X_pred = pd.DataFrame([fila])
        score  = modelo_rf.predict(X_pred)[0]

        resultados.append({
            "lugar_id":   lugar["lugar_id"],
            "nombre":     lugar["nombre"],
            "municipio":  lugar["municipio"],
            "categoria":  lugar["categoria"],
            "precio_cop": lugar["precio_entrada_cop"],
            "score_pred": round(score, 2)
        })

    return pd.DataFrame(resultados).sort_values("score_pred", ascending=False).head(top_n)

# Demo con 3 usuarios distintos
for uid in [1, 15, 42]:
    u = df_usuarios[df_usuarios["usuario_id"] == uid].iloc[0]
    print(f"\n  👤 Usuario {uid} | {u['edad']} años | de {u['ciudad_origen']} | "
          f"le gusta: {u['categoria_favorita']} | presupuesto: {u['presupuesto_preferido']} | "
          f"viaja: {u['viaja_con']}")
    print(f"  {'Top recomendaciones'}")
    recomendaciones = predecir_score_para_usuario(uid, encoders, modelo, df_lugares, df_usuarios)
    for _, r in recomendaciones.iterrows():
        precio_txt = f"${r['precio_cop']:,}" if r['precio_cop'] > 0 else "Gratis"
        print(f"    {r['score_pred']:.2f}⭐  {r['nombre']:<35} ({r['categoria']}) — {precio_txt}")

# ─────────────────────────────────────────────
# 10. EXPORTAR MODELO Y ARTEFACTOS
# ─────────────────────────────────────────────
print("\n" + "="*60)
print("9. EXPORTANDO MODELO Y ARTEFACTOS")
print("="*60)

OUTPUT = "/mnt/user-data/outputs"

# Create the output directory if it doesn't exist
os.makedirs(OUTPUT, exist_ok=True)

# Guardar modelo
with open(f"{OUTPUT}/modelo_score_visitas.pkl", "wb") as f:
    pickle.dump(modelo, f)
print("  ✓ modelo_score_visitas.pkl")

# Guardar encoders
with open(f"{OUTPUT}/encoders.pkl", "wb") as f:
    pickle.dump(encoders, f)
print("  ✓ encoders.pkl")

# Guardar importancia de features (para visualizar en la web)
importancias.to_csv(f"{OUTPUT}/feature_importance.csv", index=False)
print("  ✓ feature_importance.csv")

# Guardar métricas como JSON (para el frontend/dashboard)
metricas = {
    "modelo": "RandomForestRegressor",
    "n_estimators": 200,
    "max_depth": 12,
    "n_features": len(FEATURES),
    "n_train": len(X_train),
    "n_test": len(X_test),
    "MAE_train": round(mae_train, 4),
    "MAE_test":  round(mae_test, 4),
    "RMSE_train": round(rmse_train, 4),
    "RMSE_test":  round(rmse_test, 4),
    "R2_train": round(r2_train, 4),
    "R2_test":  round(r2_test, 4),
    "CV_R2_mean": round(cv_scores.mean(), 4),
    "CV_R2_std":  round(cv_scores.std(), 4),
    "features": FEATURES
}
with open(f"{OUTPUT}/metricas_modelo.json", "w") as f:
    json.dump(metricas, f, indent=2)
print("  ✓ metricas_modelo.json")

# Guardar predicciones del test set (para análisis)
df_pred = X_test.copy()
df_pred["y_real"] = y_test.values
df_pred["y_pred"] = y_pred_test
df_pred["error"]  = abs(df_pred["y_real"] - df_pred["y_pred"])
df_pred.to_csv(f"{OUTPUT}/predicciones_test.csv", index=False)
print("  ✓ predicciones_test.csv")

print("\n" + "="*60)
print("✅ PIPELINE COMPLETO — RESUMEN FINAL")
print("="*60)
print(f"  Modelo:       Random Forest Regressor")
print(f"  Datos usados: {len(df)} registros de visitas enriquecidos")
print(f"  Features:     {len(FEATURES)} variables")
print(f"  MAE test:     {mae_test:.4f}  (error promedio en escala 1-5)")
print(f"  R² test:      {r2_test:.4f}  (capacidad explicativa del modelo)")
print(f"  CV R²:        {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
print(f"\n  Archivos generados en {OUTPUT}/:")
print(f"    - modelo_score_visitas.pkl  (modelo listo para producción)")
print(f"    - encoders.pkl              (para decodificar predicciones)")
print(f"    - feature_importance.csv    (para el dashboard)")
print(f"    - metricas_modelo.json      (para el frontend)")
print(f"    - predicciones_test.csv     (para análisis y gráficas)")